# Generated by Django 3.2.7 on 2021-09-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_carros_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='ano',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='modelo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
        migrations.AddField(
            model_name='produtos',
            name='produto',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
