# Generated by Django 3.2.7 on 2021-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210922_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto',
            field=models.CharField(max_length=100),
        ),
    ]
