# Generated by Django 3.2.7 on 2021-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210922_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cnpj',
            field=models.CharField(default='SOME STRING', max_length=14),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
