# Generated by Django 3.2.7 on 2021-09-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210922_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='14 dígitos', max_length=14)),
                ('razaoSocial', models.CharField(default=' ', max_length=10)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('cidade', models.CharField(default=' ', max_length=20)),
                ('estado', models.CharField(default='Ex: SP', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto',
            field=models.CharField(max_length=100),
        ),
    ]
